### ISSUE TITLE
MAX_LEN_WORD issue

### ISSUE THREAD

**Issue by cvtower** [wushilian/CRNN_Attention_OCR#10]
Hello sir,

Nice job!
Here i have a question, i need to recognition long number sequence, the max length might be 20, so i just change the input W to 240(2*120=240) and change the stride of the last pooling layer from 1.2  to 2,2.
however the training will not converge whenever i add more samples(>100), and the acc is always 0.0.
Do you have any advice?

**Comment by wushilian** [comment]
@cvtower you can try just change MAXIMUM__DECODE_ITERATIONS=40,MAX_LEN_WORD=45,
Do you mean you just change image from(120,32) to (240,32),and then model didn't converge?

**Comment by cvtower** [comment]
@wushilian 
Sorry sir,
I do have made a mistake, my training set(158 samples) contains 1 wrong label, the model converges when the wrong label file is replaced, and the acc comes to about 0.6 on the val dataset(256 samples). Now i will enlarge the dataset and try again.
Thanks again for your advice!
