### ISSUE TITLE
请问你这样把宽度固定为120，效果好嘛？会不会让宽高比变形太大

### ISSUE THREAD

**Issue by zhangtao22** [wushilian/CRNN_Attention_OCR#12]
一般都是高度变为32，宽度跟随高度变化的比例变化吧？

**Comment by wushilian** [comment]
@zhangtao22 根据我的实验结果来看，实际上效果差不多。

**Comment by zhangtao22** [comment]
哥们你用的训练样本是不是图片比例，图片里面的文字宽高字数多少差不多？要不然这字体大小，字数多少，宽高比变化那么大，这样的样本训练出来效果会好？
https://github.com/da03/Attention-OCR 我看这个代码，有bucket这个概念，对应五种编解码大小，并且它高度是设置为32，但是宽度并没有定啊。但是他这样怎么确定encoder，decoder用哪种bucket的，我没有看明白

**Comment by wushilian** [comment]
@zhangtao22 你可以自己做实验对比一下

**Comment by zhangtao22** [comment]
麻烦问另外一个问题，比如我encoder阶段有16个输出，decoder阶段有11个输出，它是怎么把这16个加attention系数变成11的呢？

**Comment by zhangtao22** [comment]
我看你这个代码，encoder的输出加了attention系数以后直接给decoder做输入是吧，所以你这个输入图像的width必须固定，如果长度变了，系数就对不上了
