### ISSUE TITLE
不能训练问题

### ISSUE THREAD

**Issue by ElagJun** [wushilian/CRNN_Attention_OCR#13]
程序在运行 sess.run(tf.global_variables_initializer()) 这句时卡主了  ，过一会就强制退出来了，请问这是什么原因呢

**Comment by wushilian** [comment]
@ElagJun 能具体一点吗？报的什么错？还是电脑硬件问题

**Comment by ElagJun** [comment]
什么错误都没报，就是执行到那句的时候不往下执行了，过一会强制退出了

**Comment by wushilian** [comment]
@ElagJun 可能是你电脑问题

**Comment by ElagJun** [comment]
@wushilian 电脑是公司的服务器 应该不会有什么问题。之前也跑过别的程序，还有别的问题会导致卡住吗

**Comment by wushilian** [comment]
@ElagJun 你运行的是chines分支的程序？最好把代码贴一下，以及你确定是运行到那一句话卡住，而不是读数据卡住了

**Comment by ElagJun** [comment]
@wushilian 是chinese 分支， 我在sess.run(tf.global_variables_initializer()) 这句前后都打印标记了 ，后面的就没打 还没到读数据那块

**Comment by wushilian** [comment]
@ElagJun 这个很奇怪，看上去是没问题的

**Comment by badbubble** [comment]
@ElagJun 试试改成sess.run(tf.initialize_all_variables())

**Comment by ElagJun** [comment]
@ETCartman  依旧 不能跑 ，很是无奈  也不报什么错误
