### ISSUE TITLE
你好，这个程序可以训练中文图片并测试中文吗？我看到config.py里面把英文字母转换成数字，中文的该怎么做呢？谢谢

### ISSUE THREAD

**Issue by 12357abceg** [wushilian/CRNN_Attention_OCR#19]

**Comment by wushilian** [comment]
@12357abceg 看Chinese分支

**Comment by 12357abceg** [comment]
您好，我看到config里img = im.swapaxes(0, 1) 这一行代码，这样不是变换后字体不是乱了吗？并且本来读一段字应该是一列一列的读，这样不是一行一行的读吗？

**Comment by wushilian** [comment]
@12357abceg OPENCV读进来的图片shape是（Height，Width）
