### ISSUE TITLE
报错 Can not squeeze dim[2]

### ISSUE THREAD

**Issue by huyi1989** [wushilian/CRNN_Attention_OCR#20]
ValueError: Can not squeeze dim[2], expected a dimension of 1, got 5 for 'encode_features/Squeeze' (op: 'Squeeze') with input shapes: [?,98,5,512].
我输入的图片大小为400*80，cnn特征提取后输入到rnn时会报错，想问一下这个tf.squeeze(net, axis=2)是做了什么操作，卷积后net的维度不是[batch_size, h, w , channel]吗，对第二维做压缩是为什么？

**Comment by wushilian** [comment]
@huyi1989 因为rnn的输入是一维的，所以需要把高度压缩掉，你高度设成32应该就没问题了

**Comment by huyi1989** [comment]
@wushilian在解码过程中，定义cell = tf.contrib.rnn.GRUCell(num_units=cfg.RNN_UNITS)时，因为前面使用的双向结构，不是应该是(num_units=cfg.RNN_UNITS*2)吗？
最后看到你在进行预测的时候用了pred_decode_result = pred_outputs[0].rnn_output，为什么不用pred_decode_result = pred_outputs[0].sample_id，这样不是可以直接返回结果吗？
