### ISSUE TITLE
你好，请问怎么预测不是10个字的图片啊

### ISSUE THREAD

**Issue by sjf18** [wushilian/CRNN_Attention_OCR#27]
你好，我用你的代码训练出来的模型，只能预测对10个字的图片，但是对多于十个字或者少于十个字的图片该怎么办呢，可以做到预测不定数目字数的图片吗

**Comment by wushilian** [comment]
@sjf18 理论上是可以预测不定长的图片的，是不是你测试方法有误

**Comment by Hubert2102** [comment]
你好，我这里也是，由于训练数据都是10个字的，导致预测的时候，只有10个字的图片效果好，其他个数的图效果就差了，请问你是怎么解决的呢？ @sjf18 @wushilian
