### ISSUE TITLE
单张图片预测infer.py报错，如何解决？

### ISSUE THREAD

**Issue by MatrixPlayer** [wushilian/CRNN_Attention_OCR#29]
用infer.py预测的时候，怎么单张图片预测报错, 但是batch_size批量预测没有问题， 单张预测的问题如何解决?

**Comment by linzhi123** [comment]
请问你解决这个问题了吗？ @MatrixPlayer

**Comment by wushilian** [comment]
@MatrixPlayer 可以把单张图片复制一份变成两张图片
