### ISSUE TITLE
怎么预测

### ISSUE THREAD

**Issue by Banyueqin** [wushilian/CRNN_Attention_OCR#3]
训练完成后生成attention_ocr.ckpt-239998.data-00000-of-00001，attention_ocr.ckpt-239998.index，attention_ocr.ckpt-239998.meta，checkpoint，怎么用来对字符图片进行预测

**Comment by wushilian** [comment]
@Banyueqin 参考刚上传的infer.py,理论上每次测试的图片数要等于BATCH_SIZE，

**Comment by Banyueqin** [comment]
非常感谢，但是怎么出错了

**Comment by wushilian** [comment]
@Banyueqin 如果直接用我的代码，你需要让测试图片数目等于BATCH_SIZE，测试文件夹config里修改

**Comment by Banyueqin** [comment]
嗯，谢谢啦，我再仔细看看您的代码

**Comment by Banyueqin** [comment]
这个网络是不是也可以用来识别中文字符

**Comment by wushilian** [comment]
@Banyueqin 可以，但是要修改很多东西

**Comment by Banyueqin** [comment]
嗯，还有就是我是用的网上下的 ICDAR2017 Competition on Multi-lingual scene text detection里面的数据集训练的，感觉训练的很慢，而且效果也不好

**Comment by wushilian** [comment]
@Banyueqin 那个数据少了,用syn90k数据集较合适，attention很难训练的

**Comment by Banyueqin** [comment]
谢谢大佬

**Comment by Banyueqin** [comment]
@wushilian ，最后分类的方法是用的什么方法，softmax还是ctc

**Comment by wushilian** [comment]
@Banyueqin 是用attention的方法，可以理解为每个时刻都有一个softmax
