### ISSUE TITLE
attention模型和CTC模型效果有比较过吗

### ISSUE THREAD

**Issue by gzhcv** [wushilian/CRNN_Attention_OCR#36]
如题，想请教下您对比过CTC的效果吗，中文上哪个表现好？我的实验结果是Attention对字符尺度变化很敏感，效果比CTC差很多

**Comment by wushilian** [comment]
@gzhcv 我用tf的attention效果比ctc要差一点，但是自己实现了一个attention，效果比ctc好。attention的优点在于你可以优化很多地方，包括loss，attention计算方法等等，而ctc固定死了，不好改进。

**Comment by gzhcv** [comment]
你自己实现的attention和tf的区别是什么呢，attention优化loss是指什么呢？(像用标注信息让attetion更准？或是EditProbability?)。
我在中文上的实验是这样的，10W张合成的文本行，在真实数据上测(字符尺度和背景稍微变化)，attention的拟合能力要强一些(合成数据上验证的结果好)，但是在真实数据上就很差了(10%+的acc，猜测是因为背景的细微变化导致注意力漂移)，而 CTC的结果比较正常(60%的acc)。所以如果有大量的真实数据，attention的表现会比CTC好。

**Comment by wushilian** [comment]
@gzhcv 你这个对比实验有点问题，要么是合成数据跟真实数据gap太大，要么是attention model过拟合了。而且实际应用时候也不会只拿合成数据训练
