### ISSUE TITLE
Embedding Dimension

### ISSUE THREAD

**Issue by lmpan** [wushilian/CRNN_Attention_OCR#39]
model.py 文件里的这一句可能有问题
embeddings = tf.get_variable(name='embed_matrix',shape=[cfg.VOCAB_SIZE, cfg.VOCAB_SIZE])
embeding 被定义成 VOCAB_SIZE * VOCAB_SIZE 的矩阵
如果训练识别中文用 char_std_5990 做字典的话, 这个矩阵就是 5994 * 5994 (还有 <go>, <eos>, <unk>, <pad>4个token)
还会影响后面 decoder gru 的参数量 
这么巨大的参数量会导致模型无法收敛
训练中文需要调整 embedding dimension

**Comment by wushilian** [comment]
是这样的，这个embedding需要修改

**Comment by Lanme** [comment]
@lmpan  你好请问你修改了么？结果如何？

**Comment by lmpan** [comment]
EMBEDDING_DIM 128 就够了
一开始只用 synthetic chinese string dataset 训练, 死活都收敛不了
后来发现用 synth90k 英文数据集训练 收敛很快
把这个两个数据集合起来训练就收敛了
loss 能降到 0.02左右 准确率97%左右
图片宽度统一缩放成 200  
RNN_UNITS我改成1024了
GRU换成了LSTM
没别的改动了
