### ISSUE TITLE
准确率acc一直是0.0

### ISSUE THREAD

**Issue by lmolhw5252** [wushilian/CRNN_Attention_OCR#4]
您好，我用了你的代码，使用自己的数据集，训练的时候loss=0.0几，但是val_Decoder一直是错的，acc也一直是0.0.您知道是什么问题么？

**Comment by wushilian** [comment]
@lmolhw5252 这个代码只是用来实验的，效率并不高。至于准确率为0，应该是你的训练数据不够多
