### ISSUE TITLE
转成中文识别的错误

### ISSUE THREAD

**Issue by Banyueqin** [wushilian/CRNN_Attention_OCR#6]
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [584,256] rhs shape= [578,256]
	 [[Node: save/Assign_4 = Assign[T=DT_FLOAT, _class=["loc:@decode/decoder/attention_wrapper/gru_cell/candidate/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](decode/decoder/attention_wrapper/gru_cell/candidate/kernel, save/RestoreV2_4/_81)]]

**Comment by Banyueqin** [comment]
还有是用了one-hot来识别的吗

**Comment by wushilian** [comment]
@Banyueqin embeding还是one-hot

**Comment by Banyueqin** [comment]
现在改好了，谢谢你

**Comment by wushilian** [comment]
@Banyueqin 不客气

**Comment by ghost** [comment]
@Banyueqin  请问转成中文效果好吗？我怎么训练有错误啊

**Comment by Banyueqin** [comment]
@ccnankai ，效果还行，70%accuracy

**Comment by wushilian** [comment]
@Banyueqin 你是用多少样本训练的，汉字有多少类

**Comment by ghost** [comment]
@Banyueqin   厉害  ， 请问你都该哪里了？  charset ,我还要改什么啊？

**Comment by Banyueqin** [comment]
我把cnn改成densenet了，样本有一百多万张，汉字5000多类

**Comment by wushilian** [comment]
@Banyueqin densenet效果比cnn好吗？具体densenet结构是什么，我之前尝试densenet效果反而更差

**Comment by Banyueqin** [comment]
densenet我就是从网上找的一个

**Comment by wushilian** [comment]
@ccnankai 我增加了一个中文的分支，你可以试一下

**Comment by ghost** [comment]
@wushilian   谢谢，我正在学习你的代码

**Comment by ghost** [comment]
@wushilian    我git clone 之后看不到 chinese分支啊，请问你pull上去了吗

**Comment by wushilian** [comment]
@ccnankai 你直接在网页Chinese分支下载项目吧

**Comment by Lesley96-11** [comment]
@Banyueqin 你好，可以分享一下你改的densenet吗，最后识别自然场景的中文效果怎么样啊
