### ISSUE TITLE
请问训练和测试时候，decoer的输入不一样吧？

### ISSUE THREAD

**Issue by ghost** [wushilian/CRNN_Attention_OCR#9]
@wushilian   打扰下。
  train_decode_result = train_outputs[0].rnn_output[:, :-1, :]
  pred_decode_result = pred_outputs[0].rnn_output

请问这两句话是什么意思啊？哪里可以啊

**Comment by wushilian** [comment]
@ccnankai 训练时decoder还要把label当做输入，测试时不需要label

**Comment by ghost** [comment]
哦哦 懂了

**Comment by wushilian** [comment]
@ccnankai 去TensorFlow的官方文档看
